/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC5289Library,
  IERC5289LibraryInterface,
} from "../IERC5289Library";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "signer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint16",
        name: "documentId",
        type: "uint16",
      },
    ],
    name: "DocumentSigned",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "documentId",
        type: "uint16",
      },
    ],
    name: "documentSigned",
    outputs: [
      {
        internalType: "bool",
        name: "signed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "documentId",
        type: "uint16",
      },
    ],
    name: "documentSignedAt",
    outputs: [
      {
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "documentId",
        type: "uint16",
      },
    ],
    name: "legalDocument",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "documentId",
        type: "uint16",
      },
    ],
    name: "signDocument",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC5289Library__factory {
  static readonly abi = _abi;
  static createInterface(): IERC5289LibraryInterface {
    return new Interface(_abi) as IERC5289LibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC5289Library {
    return new Contract(address, _abi, runner) as unknown as IERC5289Library;
  }
}
