/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC5289Library",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289Library__factory>;
    getContractFactory(
      name: "ERC5289LibraryFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289LibraryFactory__factory>;
    getContractFactory(
      name: "IERC5289Library",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5289Library__factory>;

    getContractAt(
      name: "ERC5289Library",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC5289Library>;
    getContractAt(
      name: "ERC5289LibraryFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC5289LibraryFactory>;
    getContractAt(
      name: "IERC5289Library",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5289Library>;

    deployContract(
      name: "ERC5289Library",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289Library>;
    deployContract(
      name: "ERC5289LibraryFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289LibraryFactory>;
    deployContract(
      name: "IERC5289Library",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5289Library>;

    deployContract(
      name: "ERC5289Library",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289Library>;
    deployContract(
      name: "ERC5289LibraryFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC5289LibraryFactory>;
    deployContract(
      name: "IERC5289Library",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5289Library>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
  }
}
