/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IERC5289LibraryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "documentSigned"
      | "documentSignedAt"
      | "legalDocument"
      | "signDocument"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentSigned"): EventFragment;

  encodeFunctionData(
    functionFragment: "documentSigned",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "documentSignedAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "legalDocument",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signDocument",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "documentSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "documentSignedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "legalDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signDocument",
    data: BytesLike
  ): Result;
}

export namespace DocumentSignedEvent {
  export type InputTuple = [signer: AddressLike, documentId: BigNumberish];
  export type OutputTuple = [signer: string, documentId: bigint];
  export interface OutputObject {
    signer: string;
    documentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC5289Library extends BaseContract {
  connect(runner?: ContractRunner | null): IERC5289Library;
  waitForDeployment(): Promise<this>;

  interface: IERC5289LibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  documentSigned: TypedContractMethod<
    [user: AddressLike, documentId: BigNumberish],
    [boolean],
    "view"
  >;

  documentSignedAt: TypedContractMethod<
    [user: AddressLike, documentId: BigNumberish],
    [bigint],
    "view"
  >;

  legalDocument: TypedContractMethod<
    [documentId: BigNumberish],
    [string],
    "view"
  >;

  signDocument: TypedContractMethod<
    [signer: AddressLike, documentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "documentSigned"
  ): TypedContractMethod<
    [user: AddressLike, documentId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "documentSignedAt"
  ): TypedContractMethod<
    [user: AddressLike, documentId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "legalDocument"
  ): TypedContractMethod<[documentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "signDocument"
  ): TypedContractMethod<
    [signer: AddressLike, documentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DocumentSigned"
  ): TypedContractEvent<
    DocumentSignedEvent.InputTuple,
    DocumentSignedEvent.OutputTuple,
    DocumentSignedEvent.OutputObject
  >;

  filters: {
    "DocumentSigned(address,uint16)": TypedContractEvent<
      DocumentSignedEvent.InputTuple,
      DocumentSignedEvent.OutputTuple,
      DocumentSignedEvent.OutputObject
    >;
    DocumentSigned: TypedContractEvent<
      DocumentSignedEvent.InputTuple,
      DocumentSignedEvent.OutputTuple,
      DocumentSignedEvent.OutputObject
    >;
  };
}
